### ISSUE TITLE
Gitlab job hanging on apptainer push

### ISSUE THREAD

**Issue by rachelwaldon** [apptainer/apptainer#1269]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

`apptainer --version` (or `singularity --version`).

![image](https://user-images.githubusercontent.com/42785514/230745271-b2d63689-681f-4056-8de0-8f9ef5ce85c7.png)

### Expected behavior

What did you expect to see when you do...?

I have a Gitlab job that builds and pushes an image to the gitlab ci registry. I would expect it to push without hanging.

```yaml
build-sif:
  stage: build
  timeout: 2h
  script:
    - apptainer version
    - pwd
    - whoami
    - echo $CI_REGISTRY_PASSWORD | apptainer remote login --username $CI_REGISTRY_USER --password-stdin docker://$CI_REGISTRY
    - apptainer build sst.sif sst.def
    - strace -f apptainer -d push sst.sif oras://${CI_REGISTRY_IMAGE}/${CI_PROJECT_NAME}:latest
  tags: [ ubuntu_vm ]
```

### Actual behavior

What actually happened? Why was it incorrect?

The Gitlab job hangs with three dots for over 1 hour on push command.
Here is the log output by running `strace -f apptainer push -d sst.sif oras://${CI_REGISTRY_IMAGE}/${CI_PROJECT_NAME}:latest`
[strace.txt](https://github.com/apptainer/apptainer/files/11184382/strace.txt)

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

### What OS/distro are you running
![image](https://user-images.githubusercontent.com/42785514/230745386-b44756fb-5f21-47a3-bd55-c413988eeea7.png)

### How did you install Apptainer

I cloned the repo and installed from the directions here https://github.com/apptainer/apptainer/blob/main/INSTALL.md
